In [2]:
import numpy as np

# Creating arrrays

In [11]:
# 1D:
one_d = np.array([2,1,4,5,10])
print(one_d)
print('')

# 2D:
two_d = np.array([[1,2,3],[4,5,6]])
print(two_d)
print('')

# 3D:
three_d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(three_d)

[ 2  1  4  5 10]

[[1 2 3]
 [4 5 6]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Accessing Arrays

In [12]:
# 1D - Columns only
one_d = np.array([2,1,4,5,10])
print(one_d[0])
print(one_d[-1])
print(one_d[2:4])

2
10
[4 5]


In [15]:
# 2D - Rows, Columns
two_d = np.array([[1,2,3],[4,5,6]])
print(two_d[0,2])
print(two_d[:,1])
print(two_d[1:,-1])

3
[2 5]
[6]


In [17]:
# 3D - Array, Rows, Columns
three_d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(three_d[0,1,1])
print(three_d[:,0,0])

4
[1 5]


In [21]:
big_2d = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18]])
print(big_2d)
print('')

## Notation = [row_start:row_finish:row_step, col_start:col_finish:col_step]
print(big_2d[0::2,0::2])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]

[[ 1  3  5]
 [13 15 17]]


# Element-wise operations

In [30]:
arr = np.array([[1,2],[3,6]])

print(arr * 2) 
print('')
print(arr + 3)
print('')

new_arr = np.array([[2,3],[4,5]])
arr += new_arr
print(arr)

[[ 2  4]
 [ 6 12]]

[[4 5]
 [6 9]]

[[ 3  5]
 [ 7 11]]


# Logical Operations

In [34]:
arr = np.array([[1,2],[3,6]])
print(arr > 2)
print('')
print(arr == 1)
print('')
print(arr % 2 == 0)

[[False False]
 [ True  True]]

[[ True False]
 [False False]]

[[False  True]
 [False  True]]


# Looping through arrays

In [36]:
arr = np.array([[1,2],[3,6]])

for row in arr:
    print(row)
    for col in row:
        print(col)

[1 2]
1
2
[3 6]
3
6


In [52]:
three_d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

# Runs for one array [[1,2],[3,4]]
for array in three_d:
    print(array)
    print('')
    for row in array:
        print(row)
        print('')
        for col in row:
            print(col)
            print('')
    break

[[1 2]
 [3 4]]

[1 2]

1

2

[3 4]

3

4



# Numpy Methods

In [58]:
# arange (start,stop,step)
new_arr = np.arange(2,5)
print(new_arr)

skip_arr = np.arange(1,6,2)
print(skip_arr)

[2 3 4]
[1 3 5]


In [68]:
# zeros (1D: colums, 2D: rows, columns)
zero_arr = np.zeros(5)
print(zero_arr)
print('')

# ones (1D: colums, 2D: rows, columns)
one_arr = np.ones((5,5))
print(one_arr)
print('')

# eye (2D automatically)
eye_arr = np.eye(3)
print(eye_arr)

[0. 0. 0. 0. 0.]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [69]:
# Linspace (start, stop, equal spaces)
spaced = np.linspace(1,100,10)
print(spaced)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [71]:
# random (row,col)
rand_arr = np.random.randn(4,3)
print(rand_arr)

[[-0.44965273 -0.28642172  0.79793196]
 [ 0.32231759  0.33084513 -0.23902442]
 [ 1.3232914   1.40351487 -0.78736027]
 [-0.39467563 -0.17458505  0.5610924 ]]


In [72]:
# Size (rows * columns)
three_d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(np.size(three_d))

rand_arr = np.random.randn(4,3)
print(np.size(rand_arr))

8
12


In [75]:
# Shape (dimensions)
three_d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print('array, row, col')
print(np.shape(three_d))

array, row, col
(2, 2, 2)
(4, 3)


In [84]:
# reshape (array, row, col)

rand_arr = np.random.randn(1,16)
print(rand_arr)
print(np.shape(rand_arr))
print('')

rand_two_d = rand_arr.reshape(4,4)
print(rand_two_d)
print(np.shape(rand_two_d))
print('')

rand_three_d = rand_arr.reshape(2,4,2)
print(rand_three_d)
print(np.shape(rand_three_d))

[[ 0.28671302  0.00685951 -0.56556551 -1.29065004 -0.5322222   0.38101208
   0.76815798 -1.4039191   1.64026309 -0.36689021  0.49100222 -1.68742268
  -0.84822273 -0.9135087   0.60702757  0.48656815]]
(1, 16)

[[ 0.28671302  0.00685951 -0.56556551 -1.29065004]
 [-0.5322222   0.38101208  0.76815798 -1.4039191 ]
 [ 1.64026309 -0.36689021  0.49100222 -1.68742268]
 [-0.84822273 -0.9135087   0.60702757  0.48656815]]
(4, 4)

[[[ 0.28671302  0.00685951]
  [-0.56556551 -1.29065004]
  [-0.5322222   0.38101208]
  [ 0.76815798 -1.4039191 ]]

 [[ 1.64026309 -0.36689021]
  [ 0.49100222 -1.68742268]
  [-0.84822273 -0.9135087 ]
  [ 0.60702757  0.48656815]]]
(2, 4, 2)


# Math functions (element-wise)

In [85]:
# np.log(array)
# np.sin(array)
# np.exp(array)
# np.sqrt(array)

# Linear Algebra

In [88]:
# dot product
x = np.array([1,2,3])
y = np.array([4,5,6])

print(x.dot(y))

32


In [90]:
# matrix multiplication (i,j)*(j,k) = (i,k) (3,2)*(2,3) = (2,2)
x = np.array(([1,2,3], [4,5,6]))
y = np.array(([1,2], [4,5], [7,8]))

z = np.dot(x, y)

print(z)

[[30 36]
 [66 81]]


In [92]:
# Inverse (n,n) matrix needed
x = np.array(([1,2,3], [4,5,6], [4,2,1]))
print(np.linalg.inv(x))

[[ 2.33333333 -1.33333333  1.        ]
 [-6.66666667  3.66666667 -2.        ]
 [ 4.         -2.          1.        ]]


In [94]:
# Determinant
x = np.array(([1,2,3], [4,5,6], [4,2,1]))
print(np.linalg.det(x))

-3.0000000000000004


# Statistics and Probabilty

In [106]:
# mean
x = np.arange(0,50)
print(np.mean(x))

# mean along an axis
y = x.reshape(5,10)
print(np.mean(y, axis = 1))

# mean to get percent:
print(np.mean(x < 25))
print(np.mean(x < 12))

24.5
[ 4.5 14.5 24.5 34.5 44.5]
0.5
0.24


In [107]:
# median
x = np.arange(0,50)
print(np.median(x))

24.5


In [6]:
# percentiles and IQR
x = np.array([31,22,32,31,42,41,5,13,14,24,15,12,41])
x_sort = np.sort(x)
any_percentile = np.percentile(x_sort, 70)
print(any_percentile)

lower = np.percentile(x_sort, 25)
upper = np.percentile(x_sort, 75)
iqr = upper - lower
print(iqr)

31.4
18.0


In [9]:
x = np.array([31,22,32,31,42,41,5,13,14,24,15,12,41])
x_sort = np.sort(x)

all_percentiles = np.percentile(x_sort, [25, 50, 75])
print(all_percentiles)

[14. 24. 32.]


In [10]:
# Quantile vs Percentile: 
# quantile = [0,1] 0.5
# percentile = [0,100] 50

In [6]:
# standard deviation
x = np.array([31,22,32,31,42,41,5,13,14,24,15,12,41])
print(x.std())
print((max(x) - np.mean(x))/x.std()) ## How many standard deviations is the max away from the mean

# variance
print(x.var())

11.97976597849091
1.4319016068131092
143.5147928994083


In [124]:
# Normal Distribution
mean = 0
std = 1.2
norm_dist = np.random.normal(0, 12, 50)
print(norm_dist)

[-2.21193775e+00 -3.48656065e+00 -2.45527684e+01  8.46785663e+00
 -7.80113336e+00  1.68561815e+00 -8.46058325e+00 -1.35771629e+00
  3.29199592e+00 -2.18784651e+01  2.06859107e-02 -8.81315183e-01
 -4.36848174e+00 -1.38543846e+01  1.34560036e+01 -8.45191091e+00
  6.53735022e+00 -2.42591115e+01 -2.13024545e+01  1.57813452e+01
 -3.80237072e+00  2.63705529e+00  7.77137213e+00  1.48881600e+01
  2.63365139e+01  5.69496607e+00  1.40773171e+01 -2.04734426e+01
  3.50123112e+00  2.42428400e+00  1.02083747e+01  2.74431602e+00
 -1.98815320e+01 -5.05081030e+00 -1.15336815e+01 -1.60518671e+01
 -3.94011326e+00  3.40043561e+00 -1.20807002e+01  7.06381960e+00
 -1.61032525e+01 -1.07735486e+01 -5.00236119e+00 -3.87309821e+00
 -1.89359359e+00  4.40168425e+01 -3.21234370e+01  3.73504428e+00
 -2.55892619e-02 -1.24162811e+01]


In [127]:
# Binomial Distribution
trials = 50
prob = 0.6
bi_dist = np.random.binomial(trials, prob, size = (5,10))
print(bi_dist)

[[29 34 32 26 31 37 26 31 33 28]
 [28 28 25 34 27 30 36 32 35 36]
 [32 30 29 29 28 25 23 32 34 30]
 [27 27 25 31 35 26 33 28 31 31]
 [28 33 34 32 33 28 30 32 32 33]]
